# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conv.ui'
#
# Created: Sun Mar  8 16:02:47 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

import os
rootpath=os.getenv('HOME')+'/ACM'
import sys
sys.path.append(rootpath+'/src/net/config')
sys.path.append(rootpath+'/net')

sys.path.append(os.getenv('HOME')+'/caffe/python/caffe/proto')
import caffe_pb2

#print rootpath+'src/net/config'
import netConfig_pb2
from google.protobuf import text_format
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(QtGui.QWidget):
    def __init__(self,parent=None):
        super(Ui_Form,self).__init__(parent)
        self.setupUi(self)

    def setupUi(self, Form,index=0,isTrainMode=False,layerNo=4):
	self.data=''
	self.isTrainMode=isTrainMode
	self.layerNo=layerNo
	self.index=index;
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(510, 438)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 491, 401))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
	self.tab.setStyleSheet("background-color:rgb(210,225,210);")
        self.checkBoxBias = QtGui.QCheckBox(self.tab)
        self.checkBoxBias.setGeometry(QtCore.QRect(280, 40, 97, 22))
        self.checkBoxBias.setObjectName(_fromUtf8("checkBoxBias"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 150, 181, 101))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 30, 163, 61))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.spinBoxSw = QtGui.QSpinBox(self.layoutWidget_2)
        self.spinBoxSw.setObjectName(_fromUtf8("spinBoxSw"))
        self.horizontalLayout_5.addWidget(self.spinBoxSw)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.spinBoxSh = QtGui.QSpinBox(self.layoutWidget_2)
        self.spinBoxSh.setObjectName(_fromUtf8("spinBoxSh"))
        self.horizontalLayout_6.addWidget(self.spinBoxSh)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.checkBoxSl = QtGui.QCheckBox(self.tab)
        self.checkBoxSl.setGeometry(QtCore.QRect(20, 240, 97, 22))
        self.checkBoxSl.setObjectName(_fromUtf8("checkBoxSl"))
        self.checkBoxPl = QtGui.QCheckBox(self.tab)
        self.checkBoxPl.setGeometry(QtCore.QRect(270, 240, 97, 22))
        self.checkBoxPl.setObjectName(_fromUtf8("checkBoxPl"))
        self.checkBoxKl = QtGui.QCheckBox(self.tab)
        self.checkBoxKl.setGeometry(QtCore.QRect(20, 135, 97, 22))
        self.checkBoxKl.setObjectName(_fromUtf8("checkBoxKl"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 150, 181, 93))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 20, 163, 71))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.layoutWidget_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.spinBoxKw_4 = QtGui.QSpinBox(self.layoutWidget_4)
        self.spinBoxKw_4.setObjectName(_fromUtf8("spinBoxKw_4"))
        self.horizontalLayout_9.addWidget(self.spinBoxKw_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_11 = QtGui.QLabel(self.layoutWidget_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        self.spinBoxKh_4 = QtGui.QSpinBox(self.layoutWidget_4)
        self.spinBoxKh_4.setObjectName(_fromUtf8("spinBoxKh_4"))
        self.horizontalLayout_10.addWidget(self.spinBoxKh_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(270, 60, 181, 81))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget_7 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget_7.setGeometry(QtCore.QRect(0, 20, 163, 61))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_16 = QtGui.QLabel(self.layoutWidget_7)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_15.addWidget(self.label_16)
        self.comboBoxWf = QtGui.QComboBox(self.layoutWidget_7)
        self.comboBoxWf.setObjectName(_fromUtf8("comboBoxWf"))
        self.horizontalLayout_15.addWidget(self.comboBoxWf)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_17 = QtGui.QLabel(self.layoutWidget_7)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_16.addWidget(self.label_17)
        self.comboBoxBf = QtGui.QComboBox(self.layoutWidget_7)
        self.comboBoxBf.setObjectName(_fromUtf8("comboBoxBf"))
        self.horizontalLayout_16.addWidget(self.comboBoxBf)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.layoutWidget_5 = QtGui.QWidget(self.tab)
        self.layoutWidget_5.setGeometry(QtCore.QRect(270, 10, 161, 32))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_13 = QtGui.QLabel(self.layoutWidget_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_12.addWidget(self.label_13)
        self.spinBoxG = QtGui.QSpinBox(self.layoutWidget_5)
        self.spinBoxG.setObjectName(_fromUtf8("spinBoxG"))
        self.horizontalLayout_12.addWidget(self.spinBoxG)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 0, 181, 131))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 30, 163, 101))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBoxKw = QtGui.QSpinBox(self.layoutWidget)
        self.spinBoxKw.setObjectName(_fromUtf8("spinBoxKw"))
        self.horizontalLayout.addWidget(self.spinBoxKw)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinBoxKh = QtGui.QSpinBox(self.layoutWidget)
        self.spinBoxKh.setObjectName(_fromUtf8("spinBoxKh"))
        self.horizontalLayout_2.addWidget(self.spinBoxKh)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinBoxKh_2 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBoxKh_2.setObjectName(_fromUtf8("spinBoxKh_2"))
        self.horizontalLayout_3.addWidget(self.spinBoxKh_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.layoutWidget_3 = QtGui.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 270, 147, 29))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_18 = QtGui.QLabel(self.layoutWidget_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_17.addWidget(self.label_18)
        self.comboBoxWf_2 = QtGui.QComboBox(self.layoutWidget_3)
        self.comboBoxWf_2.setObjectName(_fromUtf8("comboBoxWf_2"))
        self.horizontalLayout_17.addWidget(self.comboBoxWf_2)
        self.layoutWidget_8 = QtGui.QWidget(self.tab)
        self.layoutWidget_8.setGeometry(QtCore.QRect(20, 330, 348, 29))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_8 = QtGui.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_7.addWidget(self.label_8)
        self.spinBoxDim0_2 = QtGui.QSpinBox(self.layoutWidget_8)
        self.spinBoxDim0_2.setObjectName(_fromUtf8("spinBoxDim0_2"))
        self.horizontalLayout_7.addWidget(self.spinBoxDim0_2)
        self.spinBoxDim1_2 = QtGui.QSpinBox(self.layoutWidget_8)
        self.spinBoxDim1_2.setObjectName(_fromUtf8("spinBoxDim1_2"))
        self.horizontalLayout_7.addWidget(self.spinBoxDim1_2)
        self.spinBoxDim2_2 = QtGui.QSpinBox(self.layoutWidget_8)
        self.spinBoxDim2_2.setObjectName(_fromUtf8("spinBoxDim2_2"))
        self.horizontalLayout_7.addWidget(self.spinBoxDim2_2)
        self.spinBoxDim3_2 = QtGui.QSpinBox(self.layoutWidget_8)
        self.spinBoxDim3_2.setObjectName(_fromUtf8("spinBoxDim3_2"))
        self.horizontalLayout_7.addWidget(self.spinBoxDim3_2)
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(20, 300, 348, 29))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.spinBoxDim0 = QtGui.QSpinBox(self.widget)
        self.spinBoxDim0.setObjectName(_fromUtf8("spinBoxDim0"))
        self.horizontalLayout_4.addWidget(self.spinBoxDim0)
        self.spinBoxDim1 = QtGui.QSpinBox(self.widget)
        self.spinBoxDim1.setObjectName(_fromUtf8("spinBoxDim1"))
        self.horizontalLayout_4.addWidget(self.spinBoxDim1)
        self.spinBoxDim2 = QtGui.QSpinBox(self.widget)
        self.spinBoxDim2.setObjectName(_fromUtf8("spinBoxDim2"))
        self.horizontalLayout_4.addWidget(self.spinBoxDim2)
        self.spinBoxDim3 = QtGui.QSpinBox(self.widget)
        self.spinBoxDim3.setObjectName(_fromUtf8("spinBoxDim3"))
        self.horizontalLayout_4.addWidget(self.spinBoxDim3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.textEdit = QtGui.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 471, 347))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(400, 410, 101, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(210, 10, 171, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.checkBoxBias.setText(_translate("Form", "Bias Term", None))
        self.groupBox_2.setTitle(_translate("Form", "Stride Dimensions", None))
        self.label_6.setText(_translate("Form", "Stride Width", None))
        self.label_7.setText(_translate("Form", "Stride Height", None))
        self.checkBoxSl.setText(_translate("Form", "lock them", None))
        self.checkBoxPl.setText(_translate("Form", "lock them", None))
        self.checkBoxKl.setText(_translate("Form", "lock them", None))
        self.groupBox_3.setTitle(_translate("Form", "Pad Dimensions", None))
        self.label_10.setText(_translate("Form", "Pad Width", None))
        self.label_11.setText(_translate("Form", "Pad Height", None))
        self.groupBox_4.setTitle(_translate("Form", "Filters", None))
        self.label_16.setText(_translate("Form", "Weight F", None))
        self.label_17.setText(_translate("Form", "Bias F", None))
        self.label_13.setText(_translate("Form", "Group", None))
        self.groupBox.setTitle(_translate("Form", "Kernel Dimensions", None))
        self.label_2.setText(_translate("Form", "Kernel Width", None))
        self.label_3.setText(_translate("Form", "Kernel Height", None))
        self.label_4.setText(_translate("Form", "Number", None))
        self.label_18.setText(_translate("Form", "Top", None))
        self.label_8.setText(_translate("Form", "Next      Val ", None))
        self.label_5.setText(_translate("Form", "Current Val", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Panel View", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Text View", None))
        self.pushButton.setText(_translate("Form", "Save Changes", None))
        self.label.setText(_translate("Form", "Convolution", None))
	self.setStyle()
	self.setData()
	#self.updateHandleFromUI()
	self.setTriggers()
	#self.updateData()
	
 
    def setStyle(self):
	self.textEdit.setStyleSheet("background-color:rgb(210,225,210);")
    def setData(self):
	self.netHandler=netConfig_pb2.Param()
	self.layerHandler=caffe_pb2.NetParameter();
	text_format.Merge(open(rootpath+'/net/netData.prototxt').read(),self.netHandler)
	#print self.netHandler
	if self.isTrainMode==False:
		self.data= open(self.netHandler.net[self.index].protopath).read()

	else:
		self.data=open(self.netHandler.net[selt.index].trainpath).read()
	text_format.Merge(self.data,self.layerHandler)
	self.textEdit.setText(str(self.layerHandler.layers[self.layerNo]))

    def setTriggers(self):
	self.spinBoxKw.valueChanged.connect(self.updateHandleFromUI)

    def updateHandleFromUI(self):
	currentLayer=self.layerHandler.layers[self.layerNo].convolution_param
	print 'I am called'
	currentLayer.kernel_size=self.spinBoxKw.value()

	#Final Stage
	self.layerHandler.layers[self.layerNo].convolution_param.CopyFrom(currentLayer)
	self.textEdit.setText(str(self.layerHandler.layers[self.layerNo]))

    def updateFromText(self):

	#self.spinBoxKw.setValue()


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

