# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configView.ui'
#
# Created: Fri Mar 13 16:13:50 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
#Imports begin
import sys
import os
root=os.getenv('EXPRESSO_ROOT')

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(QtGui.QWidget):
    def __init__(self,parent=None,text=None):
	self.text=text
        super(Ui_Form,self).__init__(parent)
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(611, 591)
        Form.setStyleSheet(_fromUtf8("background-color:rgb(120, 180, 120)"))
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 10, 551, 101))
        self.widget.setStyleSheet(_fromUtf8("background-color:rgb(150,195,150)"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("font: 21pt \"Ubuntu Condensed\";color:rgb(210, 225, 210)"))
        self.label.setObjectName(_fromUtf8("label"))
        self.widget1 = QtGui.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(10, 60, 521, 34))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEditDeployData = QtGui.QLineEdit(self.widget1)
        self.lineEditDeployData.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.lineEditDeployData.setObjectName(_fromUtf8("lineEditDeployData"))
        self.horizontalLayout.addWidget(self.lineEditDeployData)
        self.pushButtonDeployUpload = QtGui.QPushButton(self.widget1)
        self.pushButtonDeployUpload.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.pushButtonDeployUpload.setObjectName(_fromUtf8("pushButtonDeployUpload"))
        self.horizontalLayout.addWidget(self.pushButtonDeployUpload)
        self.pushButtonDeployView = QtGui.QPushButton(self.widget)
        self.pushButtonDeployView.setGeometry(QtCore.QRect(455, 20, 75, 32))
        self.pushButtonDeployView.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.pushButtonDeployView.setObjectName(_fromUtf8("pushButtonDeployView"))
        self.widget_2 = QtGui.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(20, 120, 551, 101))
        self.widget_2.setStyleSheet(_fromUtf8("background-color:rgb(150,195,150)"))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.label_4 = QtGui.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("font: 21pt \"Ubuntu Condensed\";color:rgb(210, 225, 210)"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.layoutWidget_3 = QtGui.QWidget(self.widget_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 60, 521, 34))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEditTrainData = QtGui.QLineEdit(self.layoutWidget_3)
        self.lineEditTrainData.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.lineEditTrainData.setObjectName(_fromUtf8("lineEditTrainData"))
        self.horizontalLayout_4.addWidget(self.lineEditTrainData)
        self.pushButtonTrainUpload = QtGui.QPushButton(self.layoutWidget_3)
        self.pushButtonTrainUpload.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.pushButtonTrainUpload.setObjectName(_fromUtf8("pushButtonTrainUpload"))
        self.horizontalLayout_4.addWidget(self.pushButtonTrainUpload)
        self.pushButtonTrainView = QtGui.QPushButton(self.widget_2)
        self.pushButtonTrainView.setGeometry(QtCore.QRect(455, 20, 75, 32))
        self.pushButtonTrainView.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.pushButtonTrainView.setObjectName(_fromUtf8("pushButtonTrainView"))
        self.widget_3 = QtGui.QWidget(Form)
        self.widget_3.setGeometry(QtCore.QRect(20, 340, 551, 161))
        self.widget_3.setStyleSheet(_fromUtf8("background-color:rgb(150,195,150)"))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.label_6 = QtGui.QLabel(self.widget_3)
        self.label_6.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("font: 21pt \"Ubuntu Condensed\";color:rgb(210, 225, 210)"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.layoutWidget_5 = QtGui.QWidget(self.widget_3)
        self.layoutWidget_5.setGeometry(QtCore.QRect(140, 40, 391, 34))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lineEditMeanPath = QtGui.QLineEdit(self.layoutWidget_5)
        self.lineEditMeanPath.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.lineEditMeanPath.setObjectName(_fromUtf8("lineEditMeanPath"))
        self.horizontalLayout_6.addWidget(self.lineEditMeanPath)
        self.pushButtonMeanUpload = QtGui.QPushButton(self.layoutWidget_5)
        self.pushButtonMeanUpload.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.pushButtonMeanUpload.setObjectName(_fromUtf8("pushButtonMeanUpload"))
        self.horizontalLayout_6.addWidget(self.pushButtonMeanUpload)
        self.label_9 = QtGui.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(30, 50, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(_fromUtf8("font: 16pt \"Ubuntu Condensed\";color:rgb(60, 90, 60)"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.checkBoxHasMean = QtGui.QCheckBox(self.widget_3)
        self.checkBoxHasMean.setGeometry(QtCore.QRect(430, 10, 101, 22))
        self.checkBoxHasMean.setStyleSheet(_fromUtf8("font: 16pt \"Ubuntu Condensed\";color:rgb(60, 90, 60)"))
        self.checkBoxHasMean.setObjectName(_fromUtf8("checkBoxHasMean"))
        self.checkBoxChannelSwap = QtGui.QCheckBox(self.widget_3)
        self.checkBoxChannelSwap.setGeometry(QtCore.QRect(400, 90, 141, 22))
        self.checkBoxChannelSwap.setStyleSheet(_fromUtf8("font: 16pt \"Ubuntu Condensed\";color:rgb(60, 90, 60)"))
        self.checkBoxChannelSwap.setObjectName(_fromUtf8("checkBoxChannelSwap"))
        self.checkBoxUseGPU = QtGui.QCheckBox(self.widget_3)
        self.checkBoxUseGPU.setGeometry(QtCore.QRect(240, 90, 91, 22))
        self.checkBoxUseGPU.setStyleSheet(_fromUtf8("font: 16pt \"Ubuntu Condensed\";color:rgb(60, 90, 60)"))
        self.checkBoxUseGPU.setObjectName(_fromUtf8("checkBoxUseGPU"))
        self.widget_5 = QtGui.QWidget(self.widget_3)
        self.widget_5.setGeometry(QtCore.QRect(50, 160, 551, 161))
        self.widget_5.setStyleSheet(_fromUtf8("background-color:rgb(150,195,150)"))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.label_12 = QtGui.QLabel(self.widget_5)
        self.label_12.setGeometry(QtCore.QRect(20, 10, 201, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(_fromUtf8("font: 16pt \"Ubuntu Condensed\";color:rgb(210, 225, 210)"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.layoutWidget_8 = QtGui.QWidget(self.widget_5)
        self.layoutWidget_8.setGeometry(QtCore.QRect(140, 40, 391, 34))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.lineEditDeployData_10 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEditDeployData_10.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.lineEditDeployData_10.setObjectName(_fromUtf8("lineEditDeployData_10"))
        self.horizontalLayout_10.addWidget(self.lineEditDeployData_10)
        self.pushButtonDeployUpload_8 = QtGui.QPushButton(self.layoutWidget_8)
        self.pushButtonDeployUpload_8.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.pushButtonDeployUpload_8.setObjectName(_fromUtf8("pushButtonDeployUpload_8"))
        self.horizontalLayout_10.addWidget(self.pushButtonDeployUpload_8)
        self.label_13 = QtGui.QLabel(self.widget_5)
        self.label_13.setGeometry(QtCore.QRect(30, 50, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(_fromUtf8("font: 16pt \"Ubuntu Condensed\";color:rgb(60, 90, 60)"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.checkBox_4 = QtGui.QCheckBox(self.widget_5)
        self.checkBox_4.setGeometry(QtCore.QRect(430, 10, 101, 22))
        self.checkBox_4.setStyleSheet(_fromUtf8("font: 16pt \"Ubuntu Condensed\";color:rgb(60, 90, 60)"))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox_5 = QtGui.QCheckBox(self.widget_5)
        self.checkBox_5.setGeometry(QtCore.QRect(400, 90, 141, 22))
        self.checkBox_5.setStyleSheet(_fromUtf8("font: 16pt \"Ubuntu Condensed\";color:rgb(60, 90, 60)"))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox_6 = QtGui.QCheckBox(self.widget_5)
        self.checkBox_6.setGeometry(QtCore.QRect(440, 120, 91, 22))
        self.checkBox_6.setStyleSheet(_fromUtf8("font: 16pt \"Ubuntu Condensed\";color:rgb(60, 90, 60)"))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.layoutWidget_9 = QtGui.QWidget(self.widget_5)
        self.layoutWidget_9.setGeometry(QtCore.QRect(30, 80, 171, 34))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_14 = QtGui.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(_fromUtf8("font: 16pt \"Ubuntu Condensed\";color:rgb(60, 90, 60)"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_11.addWidget(self.label_14)
        self.lineEditDeployData_11 = QtGui.QLineEdit(self.layoutWidget_9)
        self.lineEditDeployData_11.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.lineEditDeployData_11.setObjectName(_fromUtf8("lineEditDeployData_11"))
        self.horizontalLayout_11.addWidget(self.lineEditDeployData_11)
        self.label_15 = QtGui.QLabel(self.widget_3)
        self.label_15.setGeometry(QtCore.QRect(30, 130, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet(_fromUtf8("font: 16pt \"Ubuntu Condensed\";color:rgb(60, 90, 60)"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.layoutWidget_10 = QtGui.QWidget(self.widget_3)
        self.layoutWidget_10.setGeometry(QtCore.QRect(140, 120, 391, 34))
        self.layoutWidget_10.setObjectName(_fromUtf8("layoutWidget_10"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.comboBoxSelectModel = QtGui.QComboBox(self.layoutWidget_10)
        self.comboBoxSelectModel.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.comboBoxSelectModel.setObjectName(_fromUtf8("comboBoxSelectModel"))
        self.horizontalLayout_13.addWidget(self.comboBoxSelectModel)
        self.pushButtonModelUpload = QtGui.QPushButton(self.layoutWidget_10)
        self.pushButtonModelUpload.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.pushButtonModelUpload.setObjectName(_fromUtf8("pushButtonModelUpload"))
        self.horizontalLayout_13.addWidget(self.pushButtonModelUpload)
        self.widget2 = QtGui.QWidget(self.widget_3)
        self.widget2.setGeometry(QtCore.QRect(30, 80, 171, 34))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("font: 16pt \"Ubuntu Condensed\";color:rgb(60, 90, 60)"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.lineEditRawScale = QtGui.QLineEdit(self.widget2)
        self.lineEditRawScale.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.lineEditRawScale.setObjectName(_fromUtf8("lineEditRawScale"))
        self.horizontalLayout_9.addWidget(self.lineEditRawScale)
        self.widget_4 = QtGui.QWidget(Form)
        self.widget_4.setGeometry(QtCore.QRect(20, 230, 551, 101))
        self.widget_4.setStyleSheet(_fromUtf8("background-color:rgb(150,195,150)"))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.label_8 = QtGui.QLabel(self.widget_4)
        self.label_8.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(_fromUtf8("font: 21pt \"Ubuntu Condensed\";color:rgb(210, 225, 210)"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.layoutWidget_7 = QtGui.QWidget(self.widget_4)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 60, 521, 34))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lineEditSolverData = QtGui.QLineEdit(self.layoutWidget_7)
        self.lineEditSolverData.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.lineEditSolverData.setObjectName(_fromUtf8("lineEditSolverData"))
        self.horizontalLayout_8.addWidget(self.lineEditSolverData)
        self.pushButtonSolverUpload = QtGui.QPushButton(self.layoutWidget_7)
        self.pushButtonSolverUpload.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.pushButtonSolverUpload.setObjectName(_fromUtf8("pushButtonSolverUpload"))
        self.horizontalLayout_8.addWidget(self.pushButtonSolverUpload)
        self.pushButtonSolverView = QtGui.QPushButton(self.widget_4)
        self.pushButtonSolverView.setGeometry(QtCore.QRect(455, 20, 75, 32))
        self.pushButtonSolverView.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(210, 225, 210)"))
        self.pushButtonSolverView.setObjectName(_fromUtf8("pushButtonSolverView"))
        self.widget_6 = QtGui.QWidget(Form)
        self.widget_6.setGeometry(QtCore.QRect(20, 510, 551, 71))
        self.widget_6.setStyleSheet(_fromUtf8("background-color:rgb(180,195,150)"))
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.pushButtonSave = QtGui.QPushButton(self.widget_6)
        self.pushButtonSave.setGeometry(QtCore.QRect(450, 30, 75, 32))
        self.pushButtonSave.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(225, 225, 210)"))
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.widget3 = QtGui.QWidget(self.widget_6)
        self.widget3.setGeometry(QtCore.QRect(20, 30, 211, 34))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_11 = QtGui.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(_fromUtf8("font: 16pt \"Ubuntu Condensed\";color:rgb(90, 90, 60)"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_12.addWidget(self.label_11)
        self.lineEditName = QtGui.QLineEdit(self.widget3)
        self.lineEditName.setStyleSheet(_fromUtf8("font: 14pt \"Ubuntu Condensed\";background-color:rgb(150,150,90);color:rgb(225,225,180)"))
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.horizontalLayout_12.addWidget(self.lineEditName)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "Deploy Net", None))
        self.pushButtonDeployUpload.setText(_translate("Form", "Upload", None))
        self.pushButtonDeployView.setText(_translate("Form", "View", None))
        self.label_4.setText(_translate("Form", "Train Net", None))
        self.pushButtonTrainUpload.setText(_translate("Form", "Upload", None))
        self.pushButtonTrainView.setText(_translate("Form", "View", None))
        self.label_6.setText(_translate("Form", "Deploy Parameters", None))
        self.pushButtonMeanUpload.setText(_translate("Form", "Upload", None))
        self.label_9.setText(_translate("Form", "Mean Path", None))
        self.checkBoxHasMean.setText(_translate("Form", "has mean", None))
        self.checkBoxChannelSwap.setText(_translate("Form", "channel swap", None))
        self.checkBoxUseGPU.setText(_translate("Form", "use gpu", None))
        self.label_12.setText(_translate("Form", "Deploy Parameters", None))
        self.pushButtonDeployUpload_8.setText(_translate("Form", "Upload", None))
        self.label_13.setText(_translate("Form", "Mean Path", None))
        self.checkBox_4.setText(_translate("Form", "has mean", None))
        self.checkBox_5.setText(_translate("Form", "channel swap", None))
        self.checkBox_6.setText(_translate("Form", "use gpu", None))
        self.label_14.setText(_translate("Form", "Raw Scale       ", None))
        self.label_15.setText(_translate("Form", "Select Model", None))
        self.pushButtonModelUpload.setText(_translate("Form", "Add New Model", None))
        self.label_10.setText(_translate("Form", "Raw Scale       ", None))
        self.label_8.setText(_translate("Form", "Solver Net", None))
        self.pushButtonSolverUpload.setText(_translate("Form", "Upload", None))
        self.pushButtonSolverView.setText(_translate("Form", "View", None))
        self.pushButtonSave.setText(_translate("Form", "Save", None))
        self.label_11.setText(_translate("Form", "Name          ", None))
        self.lineEditName.setText(_translate("Form", "Untitled", None))
	self.uploadTriggers()


	
    def uploadTriggers(self):
	self.pushButtonTrainUpload.clicked.connect(self.trainUploadSlot)
	self.pushButtonDeployUpload.clicked.connect(self.deployUploadSlot)
	self.pushButtonSolverUpload.clicked.connect(self.solverUploadSlot)
	self.pushButtonMeanUpload.clicked.connect(self.meanPathUploadSlot)

    def trainUploadSlot(self):
        prevtext=root if str(self.lineEditTrainData.text())=='' else str(self.lineEditTrainData.text())
	self.lineEditTrainData.setText(QtGui.QFileDialog.getOpenFileName(self,self.tr("Open File"),prevtext))

    def deployUploadSlot(self):
        prevtext=root if str(self.lineEditDeployData.text())=='' else str(self.lineEditDeployData.text())
	self.lineEditDeployData.setText(QtGui.QFileDialog.getOpenFileName(self,self.tr("Open File"),prevtext))

    def solverUploadSlot(self):
        prevtext=root if str(self.lineEditSolverData.text())=='' else str(self.lineEditSolverData.text())
	self.lineEditSolverData.setText(QtGui.QFileDialog.getOpenFileName(self,self.tr("Open File"),prevtext))

    def meanPathUploadSlot(self):
        prevtext=root if str(self.lineEditMeanPath.text())=='' else str(self.lineEditMeanPath.text())
	self.lineEditMeanPath.setText(QtGui.QFileDialog.getOpenFileName(self,self.tr("Open File"),prevtext))



if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

