# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interpreterProto.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='interpreterProto.proto',
  package='interpreterSpecification',
  serialized_pb='\n\x16interpreterProto.proto\x12\x18interpreterSpecification\"H\n\x05Param\x12?\n\x0binterpreter\x18\x01 \x03(\x0b\x32*.interpreterSpecification.InterpreterParam\"\xaa\x02\n\x10InterpreterParam\x12\x45\n\x04type\x18\x01 \x01(\x0e\x32/.interpreterSpecification.InterpreterParam.Type:\x06\x44IRECT\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0e\x66uncDirectName\x18\n \x01(\t\x12\x10\n\x08getLines\x18\x03 \x01(\t\x12\x0f\n\x07operate\x18\x04 \x01(\t\x12\x11\n\tgetLabels\x18\x05 \x01(\t\x12\x14\n\x0cgetFunc1Name\x18\x06 \x01(\t\x12\x14\n\x0cgetFunc2Name\x18\x07 \x01(\t\x12\x13\n\x0bincludePath\x18\x08 \x03(\t\x12\x12\n\nmoduleName\x18\t \x03(\t\"\x1e\n\x04Type\x12\n\n\x06\x44IRECT\x10\x00\x12\n\n\x06\x43USTOM\x10\x01')



_INTERPRETERPARAM_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='interpreterSpecification.InterpreterParam.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DIRECT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUSTOM', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=395,
  serialized_end=425,
)


_PARAM = _descriptor.Descriptor(
  name='Param',
  full_name='interpreterSpecification.Param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interpreter', full_name='interpreterSpecification.Param.interpreter', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=52,
  serialized_end=124,
)


_INTERPRETERPARAM = _descriptor.Descriptor(
  name='InterpreterParam',
  full_name='interpreterSpecification.InterpreterParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='interpreterSpecification.InterpreterParam.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='interpreterSpecification.InterpreterParam.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='funcDirectName', full_name='interpreterSpecification.InterpreterParam.funcDirectName', index=2,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='getLines', full_name='interpreterSpecification.InterpreterParam.getLines', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operate', full_name='interpreterSpecification.InterpreterParam.operate', index=4,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='getLabels', full_name='interpreterSpecification.InterpreterParam.getLabels', index=5,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='getFunc1Name', full_name='interpreterSpecification.InterpreterParam.getFunc1Name', index=6,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='getFunc2Name', full_name='interpreterSpecification.InterpreterParam.getFunc2Name', index=7,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='includePath', full_name='interpreterSpecification.InterpreterParam.includePath', index=8,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='moduleName', full_name='interpreterSpecification.InterpreterParam.moduleName', index=9,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INTERPRETERPARAM_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=127,
  serialized_end=425,
)

_PARAM.fields_by_name['interpreter'].message_type = _INTERPRETERPARAM
_INTERPRETERPARAM.fields_by_name['type'].enum_type = _INTERPRETERPARAM_TYPE
_INTERPRETERPARAM_TYPE.containing_type = _INTERPRETERPARAM;
DESCRIPTOR.message_types_by_name['Param'] = _PARAM
DESCRIPTOR.message_types_by_name['InterpreterParam'] = _INTERPRETERPARAM

class Param(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARAM

  # @@protoc_insertion_point(class_scope:interpreterSpecification.Param)

class InterpreterParam(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INTERPRETERPARAM

  # @@protoc_insertion_point(class_scope:interpreterSpecification.InterpreterParam)


# @@protoc_insertion_point(module_scope)
