# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: netConfig.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='netConfig.proto',
  package='jaleynet',
  serialized_pb='\n\x0fnetConfig.proto\x12\x08jaleynet\"(\n\x05Param\x12\x1f\n\x03net\x18\x01 \x03(\x0b\x32\x12.jaleynet.NetParam\"\xe1\x01\n\x08NetParam\x12\x12\n\ncaffe_root\x18\x08 \x02(\t\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x11\n\tprotopath\x18\x02 \x02(\t\x12\x11\n\ttrainpath\x18\n \x02(\t\x12\x12\n\nsolverpath\x18\x0b \x02(\t\x12\x11\n\tmodelpath\x18\x03 \x02(\t\x12\x17\n\x08has_mean\x18\x04 \x01(\x08:\x05\x66\x61lse\x12\x10\n\x08meanpath\x18\x05 \x01(\t\x12\x14\n\x0c\x63hannel_swap\x18\x06 \x01(\x08\x12\x11\n\traw_scale\x18\x07 \x01(\r\x12\x12\n\x03gpu\x18\t \x01(\x08:\x05\x66\x61lse')




_PARAM = _descriptor.Descriptor(
  name='Param',
  full_name='jaleynet.Param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='net', full_name='jaleynet.Param.net', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=69,
)


_NETPARAM = _descriptor.Descriptor(
  name='NetParam',
  full_name='jaleynet.NetParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='caffe_root', full_name='jaleynet.NetParam.caffe_root', index=0,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='jaleynet.NetParam.name', index=1,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='protopath', full_name='jaleynet.NetParam.protopath', index=2,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trainpath', full_name='jaleynet.NetParam.trainpath', index=3,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solverpath', full_name='jaleynet.NetParam.solverpath', index=4,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modelpath', full_name='jaleynet.NetParam.modelpath', index=5,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='has_mean', full_name='jaleynet.NetParam.has_mean', index=6,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='meanpath', full_name='jaleynet.NetParam.meanpath', index=7,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel_swap', full_name='jaleynet.NetParam.channel_swap', index=8,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='raw_scale', full_name='jaleynet.NetParam.raw_scale', index=9,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gpu', full_name='jaleynet.NetParam.gpu', index=10,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=72,
  serialized_end=297,
)

_PARAM.fields_by_name['net'].message_type = _NETPARAM
DESCRIPTOR.message_types_by_name['Param'] = _PARAM
DESCRIPTOR.message_types_by_name['NetParam'] = _NETPARAM

class Param(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARAM

  # @@protoc_insertion_point(class_scope:jaleynet.Param)

class NetParam(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NETPARAM

  # @@protoc_insertion_point(class_scope:jaleynet.NetParam)


# @@protoc_insertion_point(module_scope)
