# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wizardProto.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wizardProto.proto',
  package='wizardFlow',
  serialized_pb='\n\x11wizardProto.proto\x12\nwizardFlow\",\n\x05Param\x12#\n\x04\x66low\x18\x01 \x03(\x0b\x32\x15.wizardFlow.FlowParam\"H\n\tFlowParam\x12\x10\n\x08heading1\x18\x01 \x02(\t\x12)\n\x07subflow\x18\x02 \x03(\x0b\x32\x18.wizardFlow.SubFlowParam\"I\n\x0cSubFlowParam\x12\x10\n\x08heading2\x18\x01 \x02(\t\x12\'\n\x08textiter\x18\x02 \x03(\x0b\x32\x15.wizardFlow.TextParam\";\n\tTextParam\x12\x10\n\x08heading3\x18\x01 \x02(\t\x12\x0c\n\x04text\x18\x02 \x02(\t\x12\x0e\n\x06imgloc\x18\x03 \x02(\t')




_PARAM = _descriptor.Descriptor(
  name='Param',
  full_name='wizardFlow.Param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flow', full_name='wizardFlow.Param.flow', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=77,
)


_FLOWPARAM = _descriptor.Descriptor(
  name='FlowParam',
  full_name='wizardFlow.FlowParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heading1', full_name='wizardFlow.FlowParam.heading1', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subflow', full_name='wizardFlow.FlowParam.subflow', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=79,
  serialized_end=151,
)


_SUBFLOWPARAM = _descriptor.Descriptor(
  name='SubFlowParam',
  full_name='wizardFlow.SubFlowParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heading2', full_name='wizardFlow.SubFlowParam.heading2', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='textiter', full_name='wizardFlow.SubFlowParam.textiter', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=153,
  serialized_end=226,
)


_TEXTPARAM = _descriptor.Descriptor(
  name='TextParam',
  full_name='wizardFlow.TextParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heading3', full_name='wizardFlow.TextParam.heading3', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='wizardFlow.TextParam.text', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imgloc', full_name='wizardFlow.TextParam.imgloc', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=228,
  serialized_end=287,
)

_PARAM.fields_by_name['flow'].message_type = _FLOWPARAM
_FLOWPARAM.fields_by_name['subflow'].message_type = _SUBFLOWPARAM
_SUBFLOWPARAM.fields_by_name['textiter'].message_type = _TEXTPARAM
DESCRIPTOR.message_types_by_name['Param'] = _PARAM
DESCRIPTOR.message_types_by_name['FlowParam'] = _FLOWPARAM
DESCRIPTOR.message_types_by_name['SubFlowParam'] = _SUBFLOWPARAM
DESCRIPTOR.message_types_by_name['TextParam'] = _TEXTPARAM

class Param(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARAM

  # @@protoc_insertion_point(class_scope:wizardFlow.Param)

class FlowParam(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FLOWPARAM

  # @@protoc_insertion_point(class_scope:wizardFlow.FlowParam)

class SubFlowParam(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SUBFLOWPARAM

  # @@protoc_insertion_point(class_scope:wizardFlow.SubFlowParam)

class TextParam(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEXTPARAM

  # @@protoc_insertion_point(class_scope:wizardFlow.TextParam)


# @@protoc_insertion_point(module_scope)
